
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> database admin ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306
      PMA_USER: shorje
      PMA_PASSWORD: "shorje"
      PMA_ABSOLUTE_URI: http://localhost:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
###< database admin ###

###> MySQL Database ###
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: shorje
      MYSQL_DATABASE: shorje
      MYSQL_USER: shorje
      MYSQL_PASSWORD: shorje
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
###< MySQL Database ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###

volumes:
  mysql_data:
