[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php bin/console cache:clear --env=prod",
    "php bin/console cache:warmup --env=prod"
]

[phases.build]
cmds = [
    "php bin/console doctrine:migrations:migrate --no-interaction --env=prod"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
