name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: 🚀 Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐘 Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd, curl, json, bcmath, soap, xmlrpc, xsl, gmp, exif, fileinfo, sodium, redis

    - name: 📥 Install Composer dependencies
      run: |
        cd shorje-api
        composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

    - name: 🔧 Setup environment
      run: |
        cd shorje-api
        cp .env.dev .env
        echo "APP_ENV=prod" >> .env
        echo "APP_DEBUG=false" >> .env
        echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db" >> .env

    - name: 🗄️ Setup SQLite database
      run: |
        cd shorje-api
        php bin/console doctrine:database:create
        php bin/console doctrine:migrations:migrate --no-interaction

    - name: 🏗️ Build for production
      run: |
        cd shorje-api
        php bin/console cache:clear --env=prod
        php bin/console cache:warmup --env=prod

    - name: 📁 Prepare GitHub Pages
      run: |
        mkdir -p gh-pages
        cp -r shorje-api/public/* gh-pages/
        cp README.md gh-pages/
        cp DEPLOYMENT.md gh-pages/
        
        # Create landing page based on branch
        if [ "${{ github.ref_name }}" == "dev" ]; then
          ENV_BADGE="🚧 STAGING ENVIRONMENT"
          ENV_COLOR="background: linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%);"
          ENV_TEXT="Development & Testing Environment"
        else
          ENV_BADGE="✅ PRODUCTION ENVIRONMENT"
          ENV_COLOR="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
          ENV_TEXT="Modern Arabic Marketplace - Live & Ready"
        fi
        
        cat > gh-pages/index.html << EOF
        <!DOCTYPE html>
        <html lang="ar" dir="rtl">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>🛒 Shorje Platform - ${{ github.ref_name == 'dev' && 'Staging' || 'Production' }}</title>
            <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;600;700&family=Tajawal:wght@300;400;500;700&display=swap" rel="stylesheet">
            <style>
                * { margin: 0; padding: 0; box-sizing: border-box; }
                body {
                    font-family: 'Cairo', 'Tajawal', Arial, sans-serif;
                    $ENV_COLOR
                    min-height: 100vh;
                    color: white;
                    overflow-x: hidden;
                }
                .container {
                    max-width: 1200px;
                    margin: 0 auto;
                    padding: 2rem;
                }
                .hero {
                    text-align: center;
                    padding: 4rem 0;
                    background: rgba(255, 255, 255, 0.1);
                    border-radius: 20px;
                    backdrop-filter: blur(10px);
                    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
                    margin-bottom: 3rem;
                }
                .hero h1 {
                    font-size: 4rem;
                    margin-bottom: 1rem;
                    background: linear-gradient(45deg, #ff6b6b, #ee5a24, #feca57);
                    -webkit-background-clip: text;
                    -webkit-text-fill-color: transparent;
                    background-clip: text;
                }
                .env-badge {
                    background: ${{ github.ref_name == 'dev' && '#ff6b6b' || '#00b894' }};
                    color: white;
                    padding: 0.5rem 1rem;
                    border-radius: 20px;
                    font-size: 0.9rem;
                    font-weight: bold;
                    margin-bottom: 1rem;
                    display: inline-block;
                }
                .btn {
                    display: inline-block;
                    padding: 1rem 2rem;
                    background: linear-gradient(45deg, #ff6b6b, #ee5a24);
                    color: white;
                    text-decoration: none;
                    border-radius: 50px;
                    font-weight: bold;
                    margin: 0.5rem;
                    transition: all 0.3s ease;
                    box-shadow: 0 4px 15px rgba(255, 107, 107, 0.4);
                }
                .btn:hover {
                    transform: translateY(-3px);
                    box-shadow: 0 6px 20px rgba(255, 107, 107, 0.6);
                }
                .version-info {
                    margin-top: 2rem;
                    padding: 1rem;
                    background: rgba(255, 255, 255, 0.1);
                    border-radius: 10px;
                    font-size: 0.9rem;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="hero">
                    <div class="env-badge">$ENV_BADGE</div>
                    <h1>🛒 Shorje Platform</h1>
                    <p>$ENV_TEXT</p>
                    
                    <a href="/app.php" class="btn">🚀 Launch Application</a>
                    <a href="https://github.com/Abudi7/Shorje-Platform" class="btn">📚 View Source</a>
                    
                    <div class="version-info">
                        <strong>Version:</strong> 1.0.0 | 
                        <strong>Branch:</strong> ${{ github.ref_name }} | 
                        <strong>Commit:</strong> ${{ github.sha }} | 
                        <strong>Build:</strong> $(date)
                    </div>
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: 📤 Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./gh-pages

    - name: 🚀 Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
